### ISSUE TITLE
Jest 25 causes `TypeError: Cannot read property 'message' of undefined`

### ISSUE THREAD

**Issue by markwoon** [mattphillips/jest-chain#22] opened 2020-02-03 22:42 UTC
**Bug**

- `package` version:  1.1.5
- `node` version:  12.14.1
- `npm` (or `yarn`) version:  yarn 1.21.1

Relevant code or config

```javascript
import React from 'react';
import {render} from '@testing-library/react';

function Test({}) {
  return <a>error</a>;
}

describe('Link - broken', () => {
  test('missing props', () => {
    const {asFragment} = render(<Test />);

    const result = asFragment().firstChild;
    console.log(result.textContent);
    expect(result)
      .toHaveTextContent('error')
      .not.toHaveAttribute('href');
  });
});
```

What you did:
What happened (please provide anything you think will help):

This code fails after updating from Jest 24 to Jest 25 with: `TypeError: Cannot read property 'message' of undefined`

**Comment by tonivj5** [comment] 2020-03-03 19:22
The problem comes from this line https://github.com/mattphillips/jest-chain/blob/master/src/chain.js#L21, because it always treats error as a match error, and when it isn't it it hides the actual (a `TypeError` for example).

@markwoon, I think jest-chain itself doesn't produce your error, to see the actual error, disable jest-chain :+1: 

I have opened a PR which fixes it #24

**Comment by markwoon** [comment] 2020-03-04 01:15
I can confirm @tonivj5's analysis.  Disabling jest-chain produced the real error.

**Comment by jeffreymeng** [comment] 2020-03-10 05:20
I'm having this same issue using enzyme-matchers for jest, however disabling it doesn't produce any errors.

This works:
```
expect(SUT.find(".class")).not.toHaveClassName("yes")
expect(SUT.find(".class")).toHaveClassName("no")
```
This doesn't:
```
expect(SUT.find(".class"))
        .not.toHaveClassName("yes")
        .toHaveClassName("no")
```
The error says `property 'toHaveClassName` doesn't exist on type void.

**Comment by nemosmithasf** [comment] 2020-07-30 19:38
I can confirm @tonivj5's analysis as well

**Comment by imjordanxd** [comment] 2020-08-18 22:56
Any update regarding this? I used to use this package before upgrading to Jest 25 and would like to continue using it

**Comment by RA80533** [comment] 2020-09-14 13:09
At the moment, the best solution to this issue is to modify the source code to reflect the changes made in @tonivj5's PR (#24) and run [`patch-package`](https://www.npmjs.com/package/patch-package).

**Comment by diegoaguilar** [comment] 2021-04-09 04:27
@imjordanxd did you figure out a solution or workaround for this?

**Comment by imjordanxd** [comment] 2021-04-09 04:33
@diegoaguilar no unfortunately not. Seems the PR to fix this is still open.

**Comment by mattphillips** [comment] 2022-09-28 16:58
Sorry for the delay in coming to this, but should be fixed in: https://www.npmjs.com/package/jest-chain/v/1.1.6

**Closed by mattphillips** 2022-09-28 16:58 UTC
